xrdb ~/.Xdefaults &
# xsetroot -solid black 
# aewm++
# awesome
# blackbox # Eh :(
# conky -d &
# dwm
# e16
# eaglemode.sh
# enlightenment_start
# fluxbox # Eh :(
gnome-session
# ion3
# musca
# mystumpwm
# oroborus
# pekwm # Eh :(
# ratpoison
# rdesktop -g 1680x1050 $IP
# rio
# subtle
# treewm
# twm
# wmii -r ~/.wmii-hg/wmiirc
# xfce4-session
# xsetroot -solid black &
# xterm
# xv -quit -root $BG &
# stumpwm
