[Desktop Entry]
Name=Shake
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Shake
MetacityTheme=Shake
IconTheme=Human
GtkColorScheme=fg_color:#585860606464,bg_color:#191919191919,text_color:#a4a4a4a4a4a4,base_color:#191919191919,selected_fg_color:#2d2d2d2d2d2d,selected_bg_color:#eaeaeaeaeaea,tooltip_fg_color:#e6e6e6e6e6e6,tooltip_bg_color:#000000000000
CursorTheme=default
CursorSize=18
BackgroundImage=/home/monkey/Pictures/ShakeSpeckle.png
